### ISSUE TITLE
Possible typo [ValueError: expected 4D input (got 2D input)]

### ISSUE THREAD

**Issue by sailordiary** [mpc001/end-to-end-lipreading#1]
https://github.com/mpc001/end-to-end-lipreading/blob/595a98806496120533e10a36c24d163309604f2b/video_only/model.py#L56

Here, after changing from "BatchNorm2d" to "BatchNorm1d" the program is able to run normally.

From official documentations of PyTorch:

> CLASS torch.nn.BatchNorm2d(num_features, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)[SOURCE]
Applies Batch Normalization over a 4D input (a mini-batch of 2D inputs with additional channel dimension) as described in the paper Batch Normalization: Accelerating Deep Network Training by Reducing Internal Covariate Shift .

Apparently it should have been 1d BatchNorm. The same typo can be found in the audio-visual model.

**Comment by mpc001** [comment]
Hi, sailordiary,

Thanks for lettming me know. I modified this typo! To my knowledge, in pytorch0.3.1.`nn.BatchNorm1d`/`nn.BatchNorm2d`/`nn.BatchNorm3d` are completely redundant as the  size checks are never get called.

Kind regards,
Pingchuan
