### ISSUE TITLE
About running time!

### ISSUE THREAD

**Issue by CXiaoDing** [mpc001/end-to-end-lipreading#16]
Hi, I also use a single 1080Ti for training. I also don't change any parameters. Why it took around 20 minutes per 1% epoch in the video-only problem.
Process: [ 4716/488766 (1%)] Loss: 6.3010 Acc:0.0000 Cost time: 1142s Estimated time:118110s
@mpc001

**Comment by xjwla** [comment]
Hi，Have you solved the problem. I encounted the same problem.
