### ISSUE TITLE
How to get the middle output of resnet34 using a pre-trained video-only model?

### ISSUE THREAD

**Issue by YiyuLuo** [mpc001/end-to-end-lipreading#19]
Hello! Thanks for your great work!
I'm wondering how to get the middle output of resnet34 using a pre-trained video-only model? Could you please offer some code examples of extracting those lip embeddings?

**Comment by mpc001** [comment]
Hi, the lip embedding extraction is not included in this repository. We include in [lipreading-tcn](https://github.com/mpc001/Lipreading_using_Temporal_Convolutional_Networks#how-to-extract-512-dim-embeddings) repository
