### ISSUE TITLE
About the convert_audio.py

### ISSUE THREAD

**Issue by Vegetebird** [mpc001/end-to-end-lipreading#22]
In "data = librosa.load(filename, sr=16000)[0]", I find the data.shape is differnt from my Mac and Ubuntu. (Maybe the reason is that the video format is ".mp4"? I get the same shape in ".mov".)

On Ubuntu, the  data.shape is (20480, ) larger than 19456. But on the Ubuntu the speed of librosa.load is too slow (maybe three days to process, I don't konw why is so slow), so I run the "convert_audio.py" on Mac (my Mac is 100 times faster than Ubuntu to run "librosa.load").

On Mac, the data.shape is (18368, ) smaller than 19456, so I run the "data = librosa.load(filename, sr=17000)[0][-19456:]" on my mac. But use your pretrained audio model, I get the accuracy is only 94.67% rather than 97.72%.  

So I have some questions. 
What is the shape you get on the  "data = librosa.load(filename, sr=16000)[0]"?
Why is the data.shape differnt from my Mac and Ubuntu?
Why is the speed so slow on Ubuntu?

**Comment by xjwla** [comment]
Hi, when I trained the audio_only, the training speed is very slow on ubuntu and gpu utilization is very low. My environment is GTX2080. How long  did it take you to train.  Thank you for your reply.
