### ISSUE TITLE
Dataloader Error while running main.py

### ISSUE THREAD

**Issue by euler16** [mpc001/end-to-end-lipreading#7]
when I run (as suggested in README) : CUDA_VISIBLE_DEVICES='0' python main.py --path '' --dataset /mnt/data/rajivratn/lrw/lipread_mp4 --mode 'temporalConv' --every-frame False  --batch-size 36 --lr 3e-4 --epochs 30 --test False

I am getting the following error:
RuntimeError: invalid argument 1: must be strictly positive at /pytorch/torch/lib/TH/generic/THTensorMath.c:2247

**Comment by euler16** [comment]
The error trace is:

Traceback (most recent call last):
 File “main.py”, line 212, in <module>
   main()
 File “main.py”, line 208, in main
   test_adam(args, use_gpu)
 File “main.py”, line 181, in test_adam
   train_test(model, dset_loaders, criterion, 0, ‘val’, optimizer, args, logger, use_gpu, save_path)
 File “main.py”, line 78, in train_test
   for batch_idx, (inputs, targets) in enumerate(dset_loaders[phase]):
 File “/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py”, line 417, in __iter__
   return DataLoaderIter(self)
 File “/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py”, line 242, in __init__
   self._put_indices()
 File “/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py”, line 290, in _put_indices
   indices = next(self.sample_iter, None)
 File “/usr/local/lib/python2.7/dist-packages/torch/utils/data/sampler.py”, line 119, in __iter__
   for idx in self.sampler:
 File “/usr/local/lib/python2.7/dist-packages/torch/utils/data/sampler.py”, line 50, in __iter__
   return iter(torch.randperm(len(self.data_source)).long())
RuntimeError: invalid argument 1: must be strictly positive at /pytorch/torch/lib/TH/generic/THTensorMath.c:2247

**Comment by euler16** [comment]
Resolved dataset path was incorrect

**Comment by wanli4717** [comment]
I'd like to ask how to load the data set. I have the data set, but I don't know where you clipped the data file to store it.
