### ISSUE TITLE
Estimated training time

### ISSUE THREAD

**Issue by astu9880** [mpc001/end-to-end-lipreading#9]
Would it be possible for the creators to provide details about specifications of the machine used to train and also estimated running time per epoch on the same machine? 
@mpc001

**Comment by mpc001** [comment]
Hi, @astu9880,
Sorry for the delay. We use a single 1080Ti for training the model. It took around 3 hours per epoch in the video-only classification problem.

**Comment by astu9880** [comment]
Alright. Thanks!

**Comment by CXiaoDing** [comment]
Hi, I also use a single 1080Ti for training. I also don't change any parameters. Why it took around 20 minutes per 1% epoch in the video-only problem.
`Process: [ 4716/488766 (1%)]	Loss: 6.3010	Acc:0.0000	Cost time: 1142s	Estimated time:118110s`
@mpc001

**Comment by xjwla** [comment]
Hi, would you tell me the running time per epoch when training in the audio_only . Thank you.
